### ISSUE TITLE
Translation: Bulgarian

### ISSUE THREAD

**Issue by DimoDimchev** [jwasham/coding-interview-university#1032]
Hi, I would be glad to contribute to this repo by translating in Bulgarian. Please let me know if I should invest my time in doing so!

**Comment by KiwiB0y** [comment]
I'm also interested in contributing to the project with Bulgarian translations. :)

**Comment by araas1369** [comment]
Hello dear banker
To deposit money from a specific German origin to your bank to your bank account 40807978702580000000
  To be deposited. Therefore, it is necessary to inquire about this account regarding the national government and banking restrictions, because the amounts received in the receipts are 453 million Euros.
Thank you for your cooperation .

**Comment by awatila** [comment]
_________________________

**Comment by KiwiB0y** [comment]
Reopening this issue because of a pending pull request. #1079
