### ISSUE TITLE
Website for Coding Interview University

### ISSUE THREAD

**Issue by Anri-Lombard** [jwasham/coding-interview-university#1122]
Hi John,

Do you think it is worth building a neat website for your curriculum with Angular? I've got some experience with it and there are a few advantages:
1. More accessible to beginners that are not comfortable with GitHub yet,
2. Easier to navigate if we can create with a router than continuously scrolling, and
3. Easy to revert back to the current format if it does not work out.

Potential disadvantage:
1. If we do not make it easy enough for users to star the repo they might not come over to do so.

But we can solve that :D

What are your thoughts?

**Comment by jwasham** [comment]
This is a good suggestion. I think having the project be more site-like makes sense. The problems I see are:

- making it easy to translate
- saving state for those who want to click the boxes and have the site remember their progress. To make sure it sticks across device, it would require some kind of registration/login and data store on the backend to track progress as well as still work when things get reorganized (which I've done several times over the years, adding and removing items)
- maintaining it because I haven't touched angular in almost 10 years.
