### ISSUE TITLE
Translation : Malayalam

### ISSUE THREAD

**Issue by muhsin-k** [jwasham/coding-interview-university#239]
I will be contributing in Malayalam language .
 [My fork](https://github.com/muhzi4u/coding-interview-university)

**Comment by muhzi4u** [comment]
@jwasham Any one working on this **malayalam** language .Could you please add to `README.md` file.Thanks.

**Comment by jwasham** [comment]
Done. Thanks for translating!

**Comment by rahulrajpl** [comment]
I am ready to contribute.

**Comment by muhzi4u** [comment]
@rahulrajpl Hi Rahul,I am already started .But if you are interested .You can move on.

**Comment by rahulrajpl** [comment]
All right. If any help is required, ping me.

**Comment by Roboneet** [comment]
I could help out too 😄

**Comment by muhzi4u** [comment]
@rahulrajpl @Roboneet I need help from both of you.Shall we close the issue ASAP? :blush:

**Comment by amirhmstu** [comment]
hello.thanks

**Comment by arvimal** [comment]
@muhzi4u, @Roboneet, @rahulrajpl 

Just a thought and personal opinion. 

Do we really require a Malayalam version of this excellent repo? Anyone who is going to follow such a translation won't be able to really understand the stuff that comes after this. IIUC, there were other translation attempts here which were pulled off due to this exact reason.

If you think differently and feel the translation is important to get this information out to the Malayalam speaking folks, feel free to correct me and go ahead.

All the very best, and thank you.

**Comment by siddiqkaithodu** [comment]
> @muhzi4u, @Roboneet, @rahulrajpl 
> 
> Just a thought and personal opinion. 
> 
> Do we really require a Malayalam version of this excellent repo? Anyone who is going to follow such a translation won't be able to really understand the stuff that comes after this. IIUC, there were other translation attempts here which were pulled off due to this exact reason.
> 
> If you think differently and feel the translation is important to get this information out to the Malayalam speaking folks, feel free to correct me and go ahead.
> 
> All the very best, and thank you.

Well said .i am a maintainer in javascript.info and i feel the same.Nobody will read these versions in malayalam because tgry dont makes sense.
also some terms cannot be represented in malayalam.means No offence .
Thank you all

**Comment by BreakB** [comment]
您好，我是布军岩，您的邮件已经收到，我会尽快回复！辛苦了。
