### ISSUE TITLE
From where to learn SQL Javascript HTML, CSS, and other front-end technologies?

### ISSUE THREAD

**Issue by 96mohitm** [jwasham/coding-interview-university#277]
Can you share from where to learn this languages? As these topics are not covered and I am finding difficulties in leaning these. Any online courses, books or related resourses.

Thanks alot for this repo helping me alot.

**Comment by jwasham** [comment]
It's been about 17 years since I learned those. I mainly used online tutorials and O'Reilly books at the time. Now there are likely a bunch of free online courses. It depends on your learning style. I like reading books, doing courses, and watching videos.
Keep in mind that you're not expected to remember the all details of SQL, HTML, and CSS. You just have to remember how they work and be able to look online when you need details.

**Comment by 96mohitm** [comment]
Thanks!
